### ISSUE TITLE
Use Python 3.7 for nox tests

### ISSUE THREAD

**Issue by nicoleczhu** [googleapis/env-tests-logging#10]
Context: 
Kokoro supports only up to GCP ubuntu 16.04. Which means Node/Go/Java images that use `apt-get` installs version 3.7, which is the majority. 

This means to integrate with env-tests-logging, we have to edit all the devrel-test images to install python 3.8 [from source](https://github.com/googleapis/testing-infra-docker/blob/ced75535439bb0223f31b54d05b16f3ff68db206/python/googleapis/python-multi/Dockerfile#L123-L146) or pyenv, or create/maintain new images. We'd do this for each version of the languages we want to run the tests in. 

Though an argument can be made we should* update all the images anyway to use pyenv.

**Comment by nicoleczhu** [comment]
PR made to Go repo to update python version in image go116: https://github.com/googleapis/testing-infra-docker/pull/125

I definitely think it's cleaner to update nox tests.

**Comment by Daniel-Sanche** [comment]
This should now be fixed on master
