### ISSUE TITLE
Generalize library to be used by other languages

### ISSUE THREAD

**Issue by nicoleczhu** [googleapis/env-tests-logging#2]
Hello, as I'm stepping through this test module for Go, starting a list of things that need to be generalized: 

- [build_container()](https://github.com/googleapis/env-tests-logging/blob/29ace84ca228f5a0d991f8cac559df382a58226a/envctl/envctl#L45) mkdir path name

**Comment by Daniel-Sanche** [comment]
Good catch. A couple options that came to mind:
- move `build_container` into each `env_script` file that uses it
- implement `build_python_container`, `build_go_container, etc in the shared `envctl` script

**Comment by nicoleczhu** [comment]
can we have build container script take in the package name? i.e. In deploy, I can call 

`build_container google-cloud-go` or `build_container nodejs-logging`, etc/
