### ISSUE TITLE
get permissions right for GAE on gcloud-java test project

### ISSUE THREAD

**Issue by daniel-sanche** [googleapis/env-tests-logging#52]
This PR is blocked because the GAE tests aren't running properly. We need to:
- run a project update command to get GAE flex running
- add puub/sub permissions to the GAE default service accoutn for GAE standard
- make sure GAE standard can destroy the environments it spins up

**Comment by minherz** [comment]
I can look into it but I cannot access `gcloud-java` project on `google.com`.

**Comment by daniel-sanche** [comment]
No worries, I've been working on this one
