### ISSUE TITLE
Add Cloud Functions support for java

### ISSUE THREAD

**Issue by daniel-sanche** [googleapis/env-tests-logging#53]
We implemented most environments in Java, but Functions still is incomplete. We may need to refactor the entire deployable away from springboot to make it work properly. I may need help from someone with more java experience

**Comment by minherz** [comment]
I think we can close it as a duplication of the #56

**Comment by daniel-sanche** [comment]
For this issue, I was referencing [creating an envctl script for Cloud Functions](https://github.com/googleapis/env-tests-logging/tree/java-others/envctl/env_scripts/java), so we can run tests against that environment. It looks like the code I wrote for the others isn't so easy to deploy on Functions

**Comment by minherz** [comment]
I will work to ensure that the provided code (in Java) works with PubSub and logs the message sent via data (expecting some kind of Json there). We can decide how to approach the envctl part when you are back.
